import Header from '../Components/header'
import Head from 'next/head'
import Image from 'next/image'
import Styles from '../styles/Home.module.css'
import HotCollections from '/Components/hotCollections'
import PartFive from '/Components/partFive'
import Footer from '/Components/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Rim Entertainment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HotCollections />
      <PartFive />
      <Footer />
    </>
  )
}
