import Header from "../Components/header";
import Head from "next/head";
import LiveAuctions from "/Components/liveAuctions";
import Explore from "/Components/explore";
import Footer from "/Components/footer";
import TopSellers from "/Components/topSellers";
import Slide from "/Components/slider/slide";
import HotCollections from "/Components/HotCollections";
import { QueryClient, QueryClientProvider, useQuery } from "react-query";
import openSeaApi from "./api/openSeaApi";

const loadAsset = openSeaApi.fetchAssets(
  "0x06012c8cf97bead5deae237070f9587f8e7a266d",
  1
);

const defaultQueryFn = async () => {
  return new Promise((resolve) => {
    resolve(loadAsset);
  });
};

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      queryFn: defaultQueryFn,
    },
  },
});

function Home() {
  const { data, error, isError, isLoading, status } = useQuery(
    ["assets"],
    loadAsset
  );
  // console.log("data", data);

  if (isLoading) {
    return <span>Loading...</span>;
  }

  if (isError) {
    return <span>Error: {error.message}</span>;
  }

  return (
    <QueryClientProvider client={queryClient}>
      <Head>
        <title>Rim Entertainment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <div style={{ maxWidth: 1400, margin: "auto" }}>
        <Slide />
        <TopSellers />
        <LiveAuctions />
        <HotCollections />
        <Explore />
      </div>
      <Footer />
    </QueryClientProvider>
  );
}
export default function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <Home />
    </QueryClientProvider>
  );
}
